summit_xl:
  joint_blw_velocity_controller:
    #type: velocity_controllers/JointVelocityController
    type: effort_controllers/JointEffortController
    joint: joint_back_left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_brw_velocity_controller:
    #type: velocity_controllers/JointVelocityController
    type: effort_controllers/JointEffortController
    joint: joint_back_right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_frw_velocity_controller:
    #type: velocity_controllers/JointVelocityController
    type: effort_controllers/JointEffortController
    joint: joint_front_right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_flw_velocity_controller:
    #type: velocity_controllers/JointVelocityController
    type: effort_controllers/JointEffortController
    joint: joint_front_left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

  # swerve drive just for simulation, the real robot has 4 mecanum wheel omni-drive
  joint_blw_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_back_left_steer
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_brw_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_back_right_steer
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_frw_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_front_right_steer
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_flw_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_front_left_steer
    pid: {p: 100.0, i: 0.01, d: 10.0}

  # scissor mechanism linear axis
  joint_scissor_position_controller:
    type: effort_controllers/JointPositionController
    joint: scissor_prismatic_joint
    pid: {p: 100.0, i: 0.01, d: 100.0}
    
  # PTZ camera controllers
  joint_pan_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_camera_pan
    pid: {p: 100.0, i: 0.01, d: 50.0}
    
  joint_tilt_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_camera_tilt
    pid: {p: 100.0, i: 0.01, d: 50.0}
  
  joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0
